name: Daily update of this mirror
on:
  schedule:
    - cron:  '10 05 * * *'

permissions:
  contents: write

jobs:
  update_mirror:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Mirror
      run: |
        cd "$GITHUB_WORKSPACE"

        mkdir -p ./svn_browser
        mkdir -p ./svn_trunk
        mkdir -p ./svn_MyJDownloaderClient
        mkdir -p ./svn_utils
        
        svn checkout --force "svn://svn.jdownloader.org/jdownloader/browser" "$GITHUB_WORKSPACE/svn_browser" &
        svn checkout --force "svn://svn.jdownloader.org/jdownloader/trunk" "$GITHUB_WORKSPACE/svn_trunk" &
        svn checkout --force "svn://svn.jdownloader.org/jdownloader/MyJDownloaderClient" "$GITHUB_WORKSPACE/svn_MyJDownloaderClient" &
        svn checkout --force "svn://svn.appwork.org/utils" "$GITHUB_WORKSPACE/svn_utils" &

        wait

        cd "$GITHUB_WORKSPACE/svn_browser" &&  svn revert -R . && svn update
        cd "$GITHUB_WORKSPACE/svn_trunk" &&  svn revert -R . && svn update
        cd "$GITHUB_WORKSPACE/svn_MyJDownloaderClient" &&  svn revert -R . && svn update
        cd "$GITHUB_WORKSPACE/svn_utils" &&  svn revert -R . && svn update

    - name: Check size
      run: |
        cd "$GITHUB_WORKSPACE"
        du -sh *

    - name: Git commit 
      run: |
        cd "$GITHUB_WORKSPACE"
        git config user.name updating-bot
        git config user.email github-actions@github.com
        
        git add -A
        git commit -m "mirroring bot - $(date '+%Y/%m/%d')"
        git push origin --force
